### ISSUE TITLE
Digital twins data isn't loaded when another person tries to login 

### ISSUE THREAD

**Issue by sanyam8182** [Azure/azure-digital-twins-graph-viewer#26]
I have added one person as a contributor to my azure account but when that person tries to view the graph viewer it gives an error message saying no data was returned from digital twins.

**Comment by nielsams** [comment]
Hi,
Adding someone to the contributor role on the Azure subscription will give access to the Digital Twins resource in the Azure portal, but not to the content of the Digital Twin itself.
 
If you want to give someone access to the graph you have to create a role assignment in Digital Twins. You do this by posting a user id and role id to the roleassignments API as described [here](https://docs.westcentralus.azuresmartspaces.net/management/swagger/ui/index#!/RoleAssignments)

Let me know if that works for you.

**Comment by sanyam8182** [comment]
I tried using the API but it returns with HTTP error code 401 "Authorization has been denied for this request", even though i am logged in. Is there a way to provide the role assignment through cloud itself ?

**Comment by nielsams** [comment]
Hi 
Unfortunately no. RoleAssignments have to be provided through the API currently. 
Please make sure you present a valid access token to the API in the Authorization header, obtained by a user that has space administrator role assigned (by default the user that created the Digital Twins instance).

Closing the issue for now, since this is likely not a GraphViewer issue.
